CREATE TABLE IF NOT EXISTS USER_DETAILS(USERNAME VARCHAR(255) PRIMARY KEY);

CREATE TABLE IF NOT EXISTS QUESTION(ID INT PRIMARY KEY, TEXT VARCHAR(255), TIMESTAMP TIMESTAMP, COUNT INT, POSITIVE_COUNT INT, USERNAME VARCHAR(255));

CREATE TABLE IF NOT EXISTS ANSWERED_QUESTIONS(ID INT, USERNAME VARCHAR(255), QUESTION_ID INT, CONSTRAINT PK_AQ PRIMARY KEY (USERNAME, QUESTION_ID));

CREATE SEQUENCE IF NOT EXISTS QUESTION_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS ANSWER_SEQ START WITH 1 INCREMENT BY 1;